# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      all-gh-actions-updates:
        patterns:
          - "*"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    groups:
      all-pip-updates:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    ignore:
      # Dependabot should not update Home Assistant as that should match the homeassistant key in hacs.json
      - dependency-name: "homeassistant"
