name: Linting

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:
  schedule:
    - cron: "0 0 * * *"

env:
  DEFAULT_PYTHON: "3.10"

jobs:
  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v4.2.2"
      - name: Setup Python ${{ env.DEFAULT_PYTHON }}
        uses: "actions/setup-python@v5.3.0"
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Install Python modules
        run: |
          pip install --constraint=requirements.txt pytest
      - name: Test suite
        run: |
          pytest
